//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        public static string AddAdress {
            get {
                return ResourceManager.GetString("AddAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        public static string AddCity {
            get {
                return ResourceManager.GetString("AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2: max character length 50.
        /// </summary>
        public static string Address2Max {
            get {
                return ResourceManager.GetString("Address2Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address successfully added!.
        /// </summary>
        public static string AddressAddedSuccess {
            get {
                return ResourceManager.GetString("AddressAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete Address: This address is associated with one or more customers and cannot be deleted. Please remove or update the associated customer records before attempting to delete this address..
        /// </summary>
        public static string AddressConstraintMessage {
            get {
                return ResourceManager.GetString("AddressConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: max character length 50.
        /// </summary>
        public static string AddressMax {
            get {
                return ResourceManager.GetString("AddressMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not selected.
        /// </summary>
        public static string AddressNotSelected {
            get {
                return ResourceManager.GetString("AddressNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address successfully updated!.
        /// </summary>
        public static string AddressUpdatedSuccess {
            get {
                return ResourceManager.GetString("AddressUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City successfully added!.
        /// </summary>
        public static string CityAddedSuccess {
            get {
                return ResourceManager.GetString("CityAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete City: This city is associated with one or more addresses and cannot be deleted. Please remove or update the associated address records before attempting to delete this city..
        /// </summary>
        public static string CityConstraintMessage {
            get {
                return ResourceManager.GetString("CityConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: max character length 50.
        /// </summary>
        public static string CityMax {
            get {
                return ResourceManager.GetString("CityMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not selected.
        /// </summary>
        public static string CityNotSelected {
            get {
                return ResourceManager.GetString("CityNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: Required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City successfully updated!.
        /// </summary>
        public static string CityUpdatedSuccess {
            get {
                return ResourceManager.GetString("CityUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country successfully added!.
        /// </summary>
        public static string CountryAddedSuccess {
            get {
                return ResourceManager.GetString("CountryAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete Country: This country is associated with one or more cities and cannot be deleted. Please remove or update the associated city records before attempting to delete this country..
        /// </summary>
        public static string CountryConstraintMessage {
            get {
                return ResourceManager.GetString("CountryConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: max character length 50.
        /// </summary>
        public static string CountryMax {
            get {
                return ResourceManager.GetString("CountryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not selected.
        /// </summary>
        public static string CountryNotSelected {
            get {
                return ResourceManager.GetString("CountryNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: Required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country successfully updated!.
        /// </summary>
        public static string CountryUpdatedSuccess {
            get {
                return ResourceManager.GetString("CountryUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: Required.
        /// </summary>
        public static string CountyRequired {
            get {
                return ResourceManager.GetString("CountyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer successfully added!.
        /// </summary>
        public static string CustomerAddedSuccess {
            get {
                return ResourceManager.GetString("CustomerAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete Customer: This customer is associated with one or more appointments and cannot be deleted. Please remove or update the associated appointment records before attempting to delete this customer..
        /// </summary>
        public static string CustomerConstraintMessage {
            get {
                return ResourceManager.GetString("CustomerConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name: max character length 45.
        /// </summary>
        public static string CustomerNameMax {
            get {
                return ResourceManager.GetString("CustomerNameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name: Required.
        /// </summary>
        public static string CustomerNameRequired {
            get {
                return ResourceManager.GetString("CustomerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not selected.
        /// </summary>
        public static string CustomerNotSelected {
            get {
                return ResourceManager.GetString("CustomerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer successfully updated!.
        /// </summary>
        public static string CustomerUpdatedSuccess {
            get {
                return ResourceManager.GetString("CustomerUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save..
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Addresses found..
        /// </summary>
        public static string NoAddressesFound {
            get {
                return ResourceManager.GetString("NoAddressesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No City found..
        /// </summary>
        public static string NoCityFound {
            get {
                return ResourceManager.GetString("NoCityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Country found..
        /// </summary>
        public static string NoCountryFound {
            get {
                return ResourceManager.GetString("NoCountryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Customers found..
        /// </summary>
        public static string NoCustomerFound {
            get {
                return ResourceManager.GetString("NoCustomerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Users found..
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: max character length 50.
        /// </summary>
        public static string PasswordMax {
            get {
                return ResourceManager.GetString("PasswordMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match Confirm Password.
        /// </summary>
        public static string PasswordMustMatch {
            get {
                return ResourceManager.GetString("PasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: invalid format 000-0000.
        /// </summary>
        public static string PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("PhoneInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: max character length 20.
        /// </summary>
        public static string PhoneMax {
            get {
                return ResourceManager.GetString("PhoneMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: Required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code: max character length 10.
        /// </summary>
        public static string PostalCodeMax {
            get {
                return ResourceManager.GetString("PostalCodeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code: Required.
        /// </summary>
        public static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Address..
        /// </summary>
        public static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select City..
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please selecte Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer..
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select User..
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully added!.
        /// </summary>
        public static string UserAddedSuccess {
            get {
                return ResourceManager.GetString("UserAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete User: This user is associated with one or more appointments and cannot be deleted. Please remove or update the associated appointment records before attempting to delete this user..
        /// </summary>
        public static string UserConstraintMessage {
            get {
                return ResourceManager.GetString("UserConstraintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: max character length 50.
        /// </summary>
        public static string UserNameMax {
            get {
                return ResourceManager.GetString("UserNameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not selected.
        /// </summary>
        public static string UserNotSelected {
            get {
                return ResourceManager.GetString("UserNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully updated!.
        /// </summary>
        public static string UserUpdatedSuccess {
            get {
                return ResourceManager.GetString("UserUpdatedSuccess", resourceCulture);
            }
        }
    }
}
